### ISSUE TITLE
Support for Material Design

### ISSUE THREAD

**Issue by dventurino** [rastating/DroidBeard#412]
It would be nice to have some Material Design in the Droidbeard app.
I started modifying the action bar colors and icons (see pull request #411)

Maybe a lighter theme and a floating button would be cool.

**Comment by dventurino** [comment]
![image](https://cloud.githubusercontent.com/assets/6681012/9966124/3c7285d2-5e3b-11e5-833e-5e61955de16d.png)

**Comment by serramat** [comment]
:+1:

**Comment by rastating** [comment]
Hey @dventurino, sounds like using the material theme as the base would help add some nice new UI features. I'm a big fan of having some sleek animations etc. in the UI, so I'm totally in support of adding this :)

The only thing I'm concerned about though is ensuring that the backwards compatibility stays in place for users who haven't updated to Android 5. Currently 29.65% of the DroidBeard users (or at least those who have installed via the Play Store) are using Android 4.0.3 - 4.4.

I'll try to give your change a test either tonight or tomorrow using an older version and see how it handles falling back to older versions. If there are any issues, it would be possible to maintain a material theme derivative and a non-material theme one by using the ```-v*``` folders (see https://developer.android.com/training/material/compatibility.html).

Have you got any features of the material theme in mind that you think would be good to add in?

**Comment by dventurino** [comment]
Hi @rastating,
I agree about maintaining backward compatibility. I was not able to test this enough to ensure you it does not break anything though, since I don't have an "old" device at hand.
Anyway, it should be possible to maintain two theme configurations as you suggested.

I don't have any specific feature in mind. But there are a few that I've implemented/seen in other apps, such as the pulldown to refresh (instead of the refresh icon) or the floating button (to add a show for example, instead of using the plus icon in the action bar).
Then there are the UI animations, but I didn't get the time to add them in any apps I've made.


On a personal note, I'd prefer the app theme to be cleaner (with more white in it), but I understand that the colors choice follows the SickBeard web interface here, to provide consistency.

**Comment by serramat** [comment]
Hi @rastating,
From @dventurino's work, I'm starting to add the Floating Menu and after the pull down refresh.
On my personal computer I have the emulator with Android 4.1.2, 4.4.4 and 5.1.1. I will test the app with these versions.

**Comment by rastating** [comment]
Hey @serramat, awesome! Look forward to seeing how it turns out :+1: 

@dventurino - although as you stated the colour scheme has been picked for keeping a consistent and familiar feel, I think the re-factoring you've done to introduce the white text and icons into the action bar and the removal of the logo and addition of the more prominent sidebar button looks a lot better, so definitely going to merge that in as it looks a lot cleaner :)

**Comment by dventurino** [comment]
@rastating great!
Beware that as I anticipated, the pngs I used for the refresh, settings and add_show buttons are not in the correct sizes for non 720p display. I'll fix this as soon as I can, maybe tomorrow.

I could not test this with older devices, so there is a chance that my modifications to NavigationDrawerFragment.java, ShowsFragment.java and main.xml have some effect on the older theme.

**Comment by dventurino** [comment]
With this commit https://github.com/dventurino/DroidBeard/commit/95f30ee6fddbc387478b7d885364141b61d29e34 I've added the correct PNGs sizes I guess. 
Can anybody try this?

**Comment by serramat** [comment]
Hey @rastating ,
@dventurino and I were thinking about something like this for the material look:
<img width="338" alt="schermata 2015-09-20 alle 13 01 02" src="https://cloud.githubusercontent.com/assets/11733072/9980393/3e26f922-5f98-11e5-8131-dc95f448d76b.png">
I picked the green color from the SickBeard logo.
What do you think?

Some of my modifications had some effect on the old theme, like the white color in the shows list and the green on the floating action button. But we can solve these once we decide how we want it to be.
<img width="315" alt="schermata 2015-09-20 alle 13 00 32" src="https://cloud.githubusercontent.com/assets/11733072/9980392/3dfdeae6-5f98-11e5-99f4-e49da0a2ca87.png">

**Comment by rastating** [comment]
@dventurino - you can combine the qualifiers on the resource directories, so in theory (I say in theory as I've not tried it before!) you should be able to have a folder named ```resources/drawable-v21-hdpi/```. I've pulled your changes into a branch of my own that I'll have a play with and see if I can fix :)

@serramat - it looks good but I still want to stick to the original core colour scheme to keep in line with Sick Beard itself, but I think some UI improvements would be good (such as the brighter white icons that @dventurino has added and the cleanup of the action bar that I can see in your screenshot). @adamprescott what do you think?

I have created a new dev branch called ```material_design``` (https://github.com/rastating/DroidBeard/tree/material_design) for these improvements.

**Comment by dventurino** [comment]
@rastating : I've added this 4e05f6a573ad23077b10fd444ad2b83414820e72.
I see that the text in the pause and delete buttons is not centered. Maybe I forgot something from styles.xml.

**Comment by serramat** [comment]
@rastating : I sent a pull request with some UI improvements and with the original colour scheme ;)

See #415

**Comment by rastating** [comment]
Thanks @serramat! will check this out and give it a look through, I've got an Android 4.4 device I'll test with and try Android 5x in an emulator :)

**Comment by rastating** [comment]
@serramat - sorry for the delay, just got around to giving the PR a test. I *really* like the pull down to refresh, feels really nice. The entire thing felt nice, there's only one thing that I think could do with being changed though, which is the floating button.

I think it'd be better if the floating button was only displayed on the shows screen, rather than on every screen, as it's a bit out of context with the other screens (this is something I had been meaning to change in the old layout for a while but never got around to) and on the settings / profile screen it overlaps some important stuff (see below)

![new_profile_overlap](https://cloud.githubusercontent.com/assets/2500434/10112106/8e4647f0-63d0-11e5-8142-43a735bfb91d.png)

Other than that minor change to only show the new show button on the shows screen, I think the changes you guys have made are really nice and it has definitely made it look cleaner and a bit more user friendly. It's a shame the action bar in pre Android 5 can't be made to look like the new one, as the version you and @dventurino have made is so much nicer than the old one!

If you feel like doing the change for the new show button feel free to send me a pull request, otherwise I'll try and get it sorted in the next week and release a new beta to the Play Store :)

**Comment by serramat** [comment]
hey @rastating, we are glad you liked our work! :-) ? I've made a new pull request #422 with the floating action button fix you asked!

**Comment by rastating** [comment]
FYI, this has been released in the v1.5 beta tonight :)

**Comment by dventurino** [comment]
@rastating great! 
Recently android studio added the possibility to create a navigation drawer like the one in the play store app without too much trouble. We could try to switch to that one. What do you think?

As for the color scheme, what do you think about maintaining the default color scheme and give users a choice to switch to the other one(s) through settings?

We've seen you added us in the credits section ;)

**Comment by rastating** [comment]
@dventurino - could you show me the kind of drawer you are referring to? I had a look in the version of the Play Store I have on my Android device but couldn't see much difference in how it opens up?

Extra colour schemes sound like a cool feature :)

I'm going to close this issue now that the original changes have been merged and deployed, but feel free to open two new issues for the navigation drawer and the extra colour schemes, sounds interesting! :)
